services:
  acmecorp:
    url: https://host.docker.internal:7157/api/OPA/BundleGet
    allow_insecure_tls : true

bundles:
  authz:
    service: acmecorp
    resource: somedir/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
