# Release branches where trunk branches are merge-committed to trigger releases

#release:
#- base-branch:
#  - 'main'
#  - 'maintenance/.+/[0-9]+\.([0-9]+|x)\.x'

# Label any maintenance branch, trunk and release

maintenance:
- base-branch:
  - 'maintenance/.+/[0-9]+\.([0-9]+|x)\.x'

# Label PRs into the main branch

#main:
#- base-branch:
#  - 'main'

# Labels for PRs on asset specific branches

egress-api-container:
- base-branch:
  - '.+/egress-api-container(/.+)?'

egress-ui-container:
- base-branch:
  - '.+/egress-ui-container(/.+)?'

main-api-container:
- base-branch:
  - '.+/main-api-container(/.+)?'

main-ui-container:
- base-branch:
  - '.+/main-ui-container(/.+)?'

tre-api-container:
- base-branch:
  - '.+/tre-api-container(/.+)?'

tre-ui-container:
- base-branch:
  - '.+/tre-ui-container(/.+)?'

tre-hasura-container:
- base-branch:
  - '.+/tre-hasura-container(/.+)?'

tre-sql-pg-container:
- base-branch:
  - '.+/tre-sql-pg-container(/.+)?'

tre-sql-trino-container:
- base-branch:
  - '.+/tre-sql-trino-container(/.+)?'
