{{- if .Values.keycloak.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  annotations:
    # "helm.sh/hook": "post-install"
spec:
  instances: {{ .Values.keycloak.postgres.replicas }} 
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: {{ .Values.keycloak.postgres.database }}
      owner: keycloak
      secret:
        name: {{ include "submission-stack.fullname" . }}-kc-pg-secret

  storage:
    size: {{ .Values.keycloak.postgres.size }}
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.keycloak.postgres.size }}
      storageClassName: {{ .Values.global.storage.defaultClass }}

  monitoring:
    enablePodMonitor: false
{{- end }}