FROM --platform=${BUILDPLATFORM} mcr.microsoft.com/dotnet/sdk:8.0.416 AS build
WORKDIR /src
COPY ["Tre-SQL-Trino/Tre-SQL-Trino.csproj", "Tre-SQL-Trino/"]
RUN dotnet restore "Tre-SQL-Trino/Tre-SQL-Trino.csproj"
COPY Tre-SQL-Trino/ Tre-SQL-Trino/
RUN dotnet publish "Tre-SQL-Trino/Tre-SQL-Trino.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore \
    --self-contained=false \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
USER app
WORKDIR /app
COPY --chown=app:app --from=build /app/publish .
ENTRYPOINT ["dotnet", "Tre-SQL-Trino.dll"]
