#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Tre-SQL-Trino/Tre-SQL-Trino.csproj", "Tre-SQL-Trino/"]
RUN dotnet restore "Tre-SQL-Trino/Tre-SQL-Trino.csproj"
COPY . .
WORKDIR "/src/Tre-SQL-Trino"
RUN dotnet build "Tre-SQL-Trino.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Tre-SQL-Trino.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Tre-SQL-Trino.dll"]