version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 32769:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=listmonk
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
    
  
######################################################
# VOLUME
######################################################
volumes:
    postgres:
      driver: local

######################################################
# networks
######################################################      
