version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 32769:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=listmonk
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_IDENTITY_OPENID_CONFIG_URL=https://auth2.ukserp.ac.uk/realms/Dare-Control/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=Dare-Control-MinIO
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=2UEwErlmIvQtwyvRT1pGyiokm5IOh4JP
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=Dare-Control-roles
      - MINIO_IDENTITY_OPENID_REDIRECT_URI=http://localhost:9001/oauth_callback
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
#  control:
#    image: harbor.ukserp.ac.uk/dare/control:1.0.0
#    restart: always
#    ports:
#      - 8088:80
#    environment:
#      CONNECTIONSTRINGS__DEFAULTCONNECTION: "Server=postgres;Port=32769;Database=DARE-Control;UserId=postgres;Password=password123;"
######################################################
# VOLUME
######################################################
volumes:
    postgres:
      driver: local
    minio_data:
      driver: local

######################################################
# networks
######################################################      
#networks:
#    default: