{{- if .Values.hasura.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hasura
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.argo.project }}
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.global.argo.destinationServer }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: {{ .Values.hasura.repoUrl }}
    chart: {{ .Values.hasura.chart }}
    targetRevision: {{ .Values.hasura.chartVersion }}
    helm:
      values: |
      {{- .Values.hasura.helmValues | toYaml | nindent 8 }}
        
{{- end }}