version: '3.5'
services:
  
  submission-ui:
    image: harbor.ukserp.ac.uk/dare-trefx/control-main-ui:1.176.2
    container_name: submission-ui
    networks:
      - sub-net
    ports:
      - "8001:80"
    depends_on:
      - submission-api

  submission-api:
    image: harbor.ukserp.ac.uk/dare-trefx/control-main-api:1.123.2
    container_name: submission-api
    environment:
      ConnectionStrings__DefaultConnection: Server=postgres;Port=5432;Database=DARE-Control;Include Error Detail=true;User Id=${PGLOGIN};Password=${PGPASSWORD};
    networks:
      - sub-net
    ports:
      - "8002:80"
    depends_on:
      postgresql_submission:
        condition: service_healthy

  postgresql_submission:
    image: docker.io/bitnami/postgresql:latest
    container_name: postgres
    restart: always
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=${PGLOGIN}
      - POSTGRESQL_DATABASE=${PGLOGIN}
      - POSTGRESQL_PASSWORD=${PGPASSWORD}
    networks:
      - sub-net
    ports:
      - "5432:5432"
    volumes:
      - 'postgresql_sub:/bitnami/postgresql'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U ${PGLOGIN} -d ${PGLOGIN}" ]


  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitdata:/var/lib/rabbitmq/
        - rabbitlogs:/var/log/rabbitmq
    networks:
      - sub-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  adminer:
#    image: harbor.chi.swan.ac.uk/nrda-v2/adminer:latest  # wodby/adminer:latest
    image: adminer:latest
    restart: always
    container_name: adminer
    networks:
      - sub-net
    ports:
      - "32767:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=postgres
    depends_on:
      postgresql_submission:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10

# Simon: will stay single disk for now as small data - if larger data MUST go mlti node/disk due to erasure encoding and performance etc
  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_IDENTITY_OPENID_CONFIG_URL=https://auth2.ukserp.ac.uk/realms/Dare-Control/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID=Dare-Control-Minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=MfjRrZJn6vL48MgCyoRn6H8Rr7sv02i0
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME=SSO_IDENTIFIER
      - MINIO_IDENTITY_OPENID_SCOPES=openid
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC=on
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y


######################################################
# VOLUME
######################################################
volumes:
    postgresql_sub:
      driver: local
    minio_data:
      driver: local
    seq_data:
      driver: local
    rabbitdata:
      driver: local
    rabbitlogs:
      driver: local

######################################################
# networks
######################################################      
networks:
  sub-net:
    driver: bridge
