{{- if .Values.global.dev }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "submission-stack.fullname" . }}-kc-pg-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  username: {{ "keycloak" | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "submission-stack.fullname" . }}-postgres-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-env-config
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  accessKey: {{ randAlphaNum 16 | quote }}
  secretKey: {{ randAlphaNum 32 | quote }}
  config.env: |
    export MINIO_ROOT_USER={{ randAlphaNum 16 | quote }}
    export MINIO_ROOT_PASSWORD={{ randAlphaNum 32 | quote }}
    export MINIO_IDENTITY_OPENID_CLIENT_ID_PRIMARY_IAM="Dare-Control-Minio"
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM="8a11bbcd-693a-4549-bda4-3e978fcf4de1"

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  username: "rabbitadmin"
  password: "rabbitpassword123!"
  type: rabbitmq
  provider: rabbitmq
  port: "5672"
  host: rabbitmq
  default_user.conf: |
    default_user = rabbitadmin
    default_pass = rabbitpassword123!


---

apiVersion: v1
kind: Secret
metadata:
  name: api-keycloak-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  secret: {{ "2e60b956-16bc-4dea-8b49-118a8baac5e5" | b64enc | quote }}
  id: {{ "Dare-Control-API" | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: ui-keycloak-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  secret: {{ "1218304e-bf92-4706-83f6-912e0b04ecb9" | b64enc | quote }}
  id: {{ "Dare-Control-UI" | b64enc | quote }}

---


apiVersion: v1
kind: Secret
metadata:
  name: seq-admin-password-hash-secret
  labels:
    {{- include "submission-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
stringData:
  password: "QIoA9mhCB/dcnZklEx46c52mQEqlSnzeeixQCl6ZVk1rTavBEdhpOE6aXBG/sUk6ndYUYSNVEuz/1Zmg9/vry52L0oIIVo8yMkt/nGKmiyqY"

{{- end }}
