# Standard ignores
**/.git
**/.vs
**/.vscode
**/.classpath
**/.dockerignore
**/.env
**/.gitignore
**/.project
**/.settings
**/.toolstarget
**/*.*proj.user
**/*.dbmdl
**/*.jfm
**/azds.yaml
**/bin/
**/obj/
**/node_modules
**/npm-debug.log
**/docker-compose*
**/Dockerfile*
**/secrets.dev.yaml
**/values.dev.yaml

# Other services not needed for this build
DARE-API/
Data-Egress-API/
Data-Egress-UI/
TRE-API/
TRE-ListFiles/
TRE-UI/
TREAgent/
Tre-Camunda/
Tre-Hasura/
Tre-SQL-PG/
Tre-SQL-Trino/
TRE.Credentials/

