name: Build containers

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/containers.yaml'
      - 'src/**'
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'main'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/containers.yaml'
      - 'src/**'
permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  containers:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v1.0.0-repo
    with:
      job-name: containers
      release-tag-format: 'v${version}-containers'

  egress-api-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: egress-api-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-egress-api
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/Data-Egress-API/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  egress-ui-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: egress-ui-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-egress-ui
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/Data-Egress-UI/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  main-api-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: main-api-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-main-api
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/DARE-API/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  main-ui-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: main-ui-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-main-ui
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/DARE-FrontEnd/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-api-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: tre-api-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-api
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/TRE-API/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-hasura-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: tre-hasura-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-hasura
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/Tre-Hasura/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-sql-pg-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: tre-sql-pg-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-sqlpg
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/Tre-SQL-PG/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-sql-trino-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: tre-sql-trino-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-sqltrino
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/Tre-SQL-Trino/Dockerfile
      build-context: src/Tre-SQL-Trino
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-ui-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.0.3-bulk-containers
    with:
      job-name: tre-ui-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-ui
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: src/TRE-UI/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
