name: Release

on:
  push:
    branches:
      - ci/create-new-release-ci-using-reusable-workflows

jobs:

  ######################################################################################################################
  # Pre-Tasks
  ######################################################################################################################

  slack:
    # Open a new PR thread on Slack for this CI run
    uses: SwanseaUniversityMedical/workflows/.github/workflows/slack-release-thread.yaml@v1.1.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  changes:
    # Detect which files have been changed on this PR's full history
    needs: slack
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes.yaml@v1.1.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      github-app-id: ${{ vars.APP_ID }}
      filters: |
        DARE-api-container:
          - '.github/workflows/release.yaml'
          - 'containers/api/**'
          - 'src/DARE-API/**'
          - 'src/BL/**'
#        chart-helloworld:
#          - './.github/workflows/on-release.yaml'
#          - './.github/workflows/slack-release-thread.yaml'
#          - './.github/workflows/changes.yaml'
#          - './.github/workflows/version.yaml'
#          - './.github/workflows/build-release-chart.yaml'
#          - './.github/workflows/test-chart.yaml'
#          - './.github/workflows/release-chart.yaml'
#          - './charts/helloworld/**'
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  ######################################################################################################################
  # Container Tasks
  ######################################################################################################################

  DARE-api-container:
    # Build the DARE api container and push it as :rc-1.0.0
    needs:
      - slack
      - changes
    if: fromJSON(needs.changes.outputs.changes).DARE-api-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-container.yaml@v1.1.0
    with:
      job-name: DARE-api-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      github-app-id: ${{ vars.APP_ID }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: TEST-${{ vars.HARBOR_REPO }}-main-api
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      build-command: |
        docker build -t $IMAGE -f src/DARE-API/Dockerfile src/
      test-command: |
        echo '0'
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}


  ######################################################################################################################
  # Chart Tasks
  ######################################################################################################################

#  chart-helloworld:
#    # Build the helloworld chart and push it as x.y.z-rc
#    needs:
#      - slack
#      - changes
#    if: fromJSON(needs.changes.outputs.changes).chart-helloworld == 'true'
#    uses: ./.github/workflows/on-release-chart.yaml
#    with:
#      job-name: chart-helloworld
#      chart-registry: ${{ vars.HARBOR_REGISTRY }}
#      chart-registry-user: ${{ vars.HARBOR_USER }}
#      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
#      chart-registry-repo: helloworld
#      github-app-id: ${{ vars.APP_ID }}
#      slack-channel: ${{ vars.SLACK_CHANNEL }}
#      slack-thread: ${{ needs.slack.outputs.thread }}
#      chart: charts/helloworld
#      test-command: |
#        helm template $CHART --values charts/helloworld/values.yaml
#    secrets:
#      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
#      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
#      slack-token: ${{ secrets.SLACK_TOKEN }}

  ######################################################################################################################
  # Post-Tasks
  ######################################################################################################################

  slack-update:
    # Update the original Slack message with the final workflow status
    # WARNING! ALL UPSTREAM JOBS MUST BE DECLARED HERE TO REPORT FAILURES CORRECTLY!
    needs:
      - slack
      - changes
      - DARE-api-container
      #- chart-helloworld

    uses: SwanseaUniversityMedical/workflows/.github/workflows/slack-release-thread.yaml@v1.1.0
    if: always()
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      status: ${{ contains(join(needs.*.result, ','), 'failure') && ':no_entry:' || ':white_check_mark:' }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}