name: TRE Hasura Container

on:
  pull_request:
    paths:
      - 'src/Tre-Hasura/**'
      - 'src/BL/**'
  push:
    branches:
      - main
    paths:
      - 'src/Tre-Hasura/**'
      - 'src/BL/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tre-hasura-container:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v1.9.1-containers
    with:
      job-name: tre-hasura-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-hasura
      release-tag-format: 'DARE-TRE-HASURA-Container-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: src/Tre-Hasura/Dockerfile
      build-context: src
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
