name: TRE SQL Trino Container

on:
  pull_request:
    # Ignore PRs on branches specifically intended for other assets
    branches-ignore:
      - '*/egress-api-container*'
      - '*/egress-ui-container*'
      - '*/main-api-container*'
      - '*/main-ui-container*'
      - '*/tre-api-container*'
      - '*/tre-ui-container*'
      - '*/tre-hasura-container*'
      - '*/tre-sql-pg-container*'
    # Only consider PRs that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/tre-sql-trino-container.yaml'
      - 'src/Tre-SQL-Trino/**'
    # Make sure all workflows that are "required checks" for a given
    # branch protection rule have the same paths: and branches-ignore:
    # filters. Otherwise, you can end up in a deadlock waiting on a
    # required check that will never be executed.
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - 'maintenance/tre-sql-trino-container/[0-9]+.x.x'
      - 'maintenance/tre-sql-trino-container/[0-9]+.[0-9]+.x'
      - 'main'
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - '.github/workflows/tre-sql-trino-container.yaml'
      - 'src/Tre-SQL-Trino/**'

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Needed to generate releases safely
  cancel-in-progress: false

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  tre-sql-trino-container:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-container.yaml@v2.0.1-containers
    with:
      job-name: tre-sql-trino-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-sqltrino
      release-tag-format: 'DARE-TRE-SQLTRINO-Container-${version}'
      release-branches: |
        [
          'maintenance/tre-sql-trino-container/[0-9]+\.([0-9]+|x)\.x',
          'main'
        ]
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: src/Tre-SQL-Trino/Dockerfile
      build-context: src/Tre-SQL-Trino
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
